# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestFluxocompra():
  AD_BLOCK_LIST = [
        "*://*.doubleclick.net/*",
        "*://*.googlesyndication.com/*",
        "*://*.googleadservices.com/*",
        "*://*.googletagservices.com/*",
        "*://*.adservice.google.com/*",
        "*://*.adsystem.com/*",
        "*://*.adnxs.com/*",
        "*://*.facebook.net/*",
        "*://*.taboola.com/*",
        "*://*.outbrain.com/*",]   



  def setup_method(self, method):
    options = Options()
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
    self.driver.implicitly_wait(10)
    chrome_options = Options()
    chrome_options.add_argument("--start-maximized")
    self.driver.execute_cdp_cmd("Network.enable", {})
    self.driver.execute_cdp_cmd("Network.setBlockedURLs", {
        "urls": self.AD_BLOCK_LIST
    })


  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fluxocompra(self):
    self.driver.get("https://automationteststore.com/")
    self.driver.set_window_size(1936, 1048)

    #login
    self.driver.find_element(By.LINK_TEXT, "Login or register").click()
    self.driver.find_element(By.ID, "loginFrm_loginname").click()
    self.driver.find_element(By.ID, "loginFrm_loginname").send_keys("yagovictor22")
    self.driver.find_element(By.ID, "loginFrm_password").send_keys("Yagovictor22#")
    self.driver.find_element(By.ID, "loginFrm_password").send_keys(Keys.ENTER)

    #comprar
    self.driver.find_element(By.CSS_SELECTOR, ".nav-pills > li:nth-child(2) > a").click()
    self.driver.find_element(By.LINK_TEXT, "T-shirts").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-3:nth-child(2) .fa").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".bgnone").text == "Designer Men Casual Formal Double Cuffs Grandad Band Collar Shirt Elegant Tie"
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "SHOPPING CART"

    #logout
    self.driver.find_element(By.CSS_SELECTOR, ".fa-trash-o").click()

    self.driver.get("https://automationteststore.com/index.php?rt=account/logout")

    wait = WebDriverWait(self.driver, 10)
    assert wait.until(expected_conditions.visibility_of_element_located(
     (By.CSS_SELECTOR, ".maintext")
    )).text == "ACCOUNT LOGOUT"
    