# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestloginnegativo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testloginnegativo(self):
    self.driver.get("https://automationteststore.com/")
    self.driver.set_window_size(1936, 1048)
    assert self.driver.find_element(By.LINK_TEXT, "Login or register").text == "Login or register"
    self.driver.find_element(By.LINK_TEXT, "Login or register").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "ACCOUNT LOGIN"
    self.driver.find_element(By.ID, "loginFrm_loginname").click()
    self.driver.find_element(By.ID, "loginFrm_loginname").send_keys("yagovictor27")
    self.driver.find_element(By.ID, "loginFrm_password").send_keys("Yagovictor27")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(7)").click()
    assert "Error: Incorrect login or password provided." in self.driver.find_element(By.CSS_SELECTOR, ".alert").text