# Generated by Selenium IDE
from xml.dom.xmlbuilder import Options

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestCriacaousuario():
  AD_BLOCK_LIST = [
        "*://*.doubleclick.net/*",
        "*://*.googlesyndication.com/*",
        "*://*.googleadservices.com/*",
        "*://*.googletagservices.com/*",
        "*://*.adservice.google.com/*",
        "*://*.adsystem.com/*",
        "*://*.adnxs.com/*",
        "*://*.facebook.net/*",
        "*://*.taboola.com/*",
        "*://*.outbrain.com/*",]   



  def setup_method(self, method):
    options = Options()
    self.driver = webdriver.Chrome(options=options)
    self.driver.execute_cdp_cmd("Network.enable", {})
    self.driver.execute_cdp_cmd("Network.setBlockedURLs", {
        "urls": self.AD_BLOCK_LIST
    })



  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criacaousuario(self):
    self.driver.get("https://automationteststore.com/")
    self.driver.set_window_size(1936, 1048)
    assert self.driver.find_element(By.LINK_TEXT, "Login or register").text == "Login or register"
    self.driver.find_element(By.LINK_TEXT, "Login or register").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "ACCOUNT LOGIN"
    assert self.driver.find_element(By.CSS_SELECTOR, ".newcustomer > .heading2").text == "I AM A NEW CUSTOMER."
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "CREATE ACCOUNT"
    self.driver.find_element(By.ID, "AccountFrm_firstname").click()
    self.driver.find_element(By.ID, "AccountFrm_firstname").send_keys("Yago Victor")
    self.driver.find_element(By.ID, "AccountFrm_lastname").click()
    self.driver.find_element(By.ID, "AccountFrm_lastname").send_keys("da silva")
    self.driver.find_element(By.ID, "AccountFrm_email").send_keys("yago_victor09@gmail.com")
    self.driver.find_element(By.ID, "AccountFrm_telephone").send_keys("55(48)99926-7821")
    self.driver.find_element(By.ID, "AccountFrm_address_1").click()
    self.driver.find_element(By.ID, "AccountFrm_address_1").send_keys("Rua 1980")
    self.driver.find_element(By.ID, "AccountFrm_address_2").click()
    self.driver.find_element(By.ID, "AccountFrm_address_2").send_keys("371")
    self.driver.find_element(By.ID, "AccountFrm_city").click()
    self.driver.find_element(By.ID, "AccountFrm_city").send_keys("Balneário Camburiú")
    self.driver.find_element(By.ID, "AccountFrm_country_id").click()
    dropdown = self.driver.find_element(By.ID, "AccountFrm_country_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Brazil']").click()
    self.driver.find_element(By.ID, "AccountFrm_postcode").click()
    self.driver.find_element(By.ID, "AccountFrm_postcode").send_keys("88330491")
    self.driver.find_element(By.ID, "AccountFrm_zone_id").click()
    self.driver.find_element(By.ID, "AccountFrm_loginname").click()
    dropdown = self.driver.find_element(By.ID, "AccountFrm_zone_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Santa Catarina']").click()
    self.driver.find_element(By.ID, "AccountFrm_loginname").send_keys("yagovictor27")
    self.driver.find_element(By.ID, "AccountFrm_password").click()
    self.driver.find_element(By.ID, "AccountFrm_password").send_keys("Yagovictor22#")
    self.driver.find_element(By.ID, "AccountFrm_confirm").send_keys("Yagovictor22#")
    self.driver.find_element(By.ID, "AccountFrm_agree").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lock-on-click").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h1.heading1 > span").text == "YOUR ACCOUNT HAS BEEN CREATED!"
    self.driver.find_element(By.CSS_SELECTOR, ".side_account_list li:last-child a").click()
  
