# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestLoginpositivo():
  AD_BLOCK_LIST = [
    "*://*.doubleclick.net/*",
    "*://*.googlesyndication.com/*",
    "*://*.googleadservices.com/*",
    "*://*.googletagservices.com/*",
    "*://*.adservice.google.com/*",
    "*://*.adsystem.com/*",
    "*://*.adnxs.com/*",
    "*://*.facebook.net/*",
    "*://*.taboola.com/*",
    "*://*.outbrain.com/*",]   



  def setup_method(self, method):
    options = Options()
    self.driver = webdriver.Chrome(options=options)
    self.vars = ()
    self.driver.implicitly_wait(10)
    self.driver.execute_cdp_cmd("Network.enable", {})
    self.driver.execute_cdp_cmd("Network.setBlockedURLs", {
        "urls": self.AD_BLOCK_LIST
  
    })


  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginpositivo(self):
    self.driver.get("https://automationteststore.com/")
    self.driver.set_window_size(1936, 1048)


    
    assert self.driver.find_element(By.LINK_TEXT, "Login or register").text == "Login or register"
    self.driver.find_element(By.LINK_TEXT, "Login or register").click()
    self.driver.find_element(By.ID, "loginFrm_loginname").click()
    self.driver.find_element(By.ID, "loginFrm_loginname").send_keys("yagovictor22")
    self.driver.find_element(By.ID, "loginFrm_password").send_keys("Yagovictor22#")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(7)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "MY ACCOUNT"
    assert self.driver.find_element(By.LINK_TEXT, "Logoff").text == "  Logoff"
    self.driver.find_element(By.LINK_TEXT, "Logoff").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".maintext").text == "ACCOUNT LOGOUT"
  
